### ISSUE TITLE
Labels duplication when using simplify_clip_resolution/ST_ClipByBox2d

### ISSUE THREAD

**Issue by rochoa** [CartoDB/Windshaft-cartodb#722]
Configuring the application to clip the geometries with ST_ClipByBox2d, like in:

```diff
--- NO CLIPPING
+++ ST_ClipByBox2d via simplify_clip_resolution
@@ -41,6 +41,7 @@
     // Supported labels: 'user_id', 'user_password' (both read from redis)
     ,postgres_auth_pass: '<%= user_password %>'
     ,postgres: {
+        simplify_clip_resolution: 10000,
         "simplify_geometries":false,
         "user":"publicuser",
         "password":"public",
```

And using the `world_borders_hd` dataset with a CartoCSS with labels like:

```css
#layer {
  polygon-fill: #374C70;
  polygon-opacity: 0.9;
}
#layer::labels {
  text-name: [name];
  text-face-name: 'DejaVu Sans Book';
  text-size: 10;
  text-fill: #FFFFFF;
}
```

The labels, when getting to some zoom level, get duplicated:

![screen shot 2017-08-07 at 17 30 01](https://user-images.githubusercontent.com/45346/29033664-11140422-7b96-11e7-944b-893e408aa846.png)
