### ISSUE TITLE
Is tile aggregation count operation available?

### ISSUE THREAD

**Issue by oriolbx** [CartoDB/Windshaft-cartodb#947]
## Question

Is the count operation available for tile aggregation feature? In [this section](https://github.com/CartoDB/carto.js/blob/master/src/api/v4/layer/aggregation.js#L11) of the carto.js v4 repository, it looks like it isn't. However, I've managed to use the count operation on a Named map and carto.js v3.15

## Context 

When creating a Named Map, I'm using the new tile aggregation operations to try to create a cluster map, I managed to do it by using the count aggregation in the next named map template:

```json
{
    "template": {
        "auth": {
            "method": "open"
        },
        "version": "0.0.1",
        "name": "tile_agg_test",
        "layergroup": {
            "version": "1.5.0",
            "layers": [
                {
                    "type": "mapnik",
                    "options": {
                        "cartocss_version": "2.1.1",
                        "cartocss": "#layer { marker-fill: red; marker-width: [total];}",
                        "sql": "select * from stormevents_locations_2014",
                        "aggregation": {
                            "placement": "centroid",
                            "columns": {
                                "total": {
                                    "aggregate_function": "count",
                                    "aggregated_column": "cartodb_id"
                                }
                            },
                            "resolution": 2,
                            "threshold": 10000
                        }
                    }
                }
            ]
        },
        "view": {
            "zoom": 3,
            "center": {
                "lng": 0,
                "lat": 0
            }
        },
        "placeholders": {}
    }
}
```

And when using the template of the named map with Carto.js v3.15 it renders correctly.

However, if I add labels to the CartoCSS of the template using the result of the aggregation for the `text-name` parameter, CARTO returns an error because it can't find the aggregation column. 

```css
"#layer { marker-fill: red; marker-width: [total];}",
#layer::labels {text-name: [total]; text-face-name: 'DejaVu Sans Book'; text-size: 10; text-fill:
 #FFFFFF; text-label-position-tolerance: 0; text-halo-radius: 1; text-halo-fill: #6F808D; text-allow-
overlap: true; text-placement: point; text-placement-type: dummy; }
```

The same problem happens when I use the aggregation, SQL query and CartoCSS of the template `tile_agg_test` with CARTO.js v4. CARTO can't instantiate the map because it can't find the resulting field of the aggregation using the count operation.

However, if I use the sum operation the aggregation works in both Carto.js v4 and Named map with carto.js v3.15. [Here](http://bl.ocks.org/oriolbx/3132889b19afa3da64cea25a30ac0448) you can find the example of using the sum operation of the tiles aggregation to create a cluster map.
