### ISSUE TITLE
Use original query to compute TurboCarto ramps when points are aggregated 

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/Windshaft-cartodb#957]
Part of https://github.com/CartoDB/product/issues/30.

It seems that, when point aggregation is enabled, TurboCarto ramps are currently computed using the aggregated query, instead of the original one. We tried to enable Default Point Aggregation in Builder, and realised that colors and legends where different when aggregation was enabled (see [this comment](https://github.com/CartoDB/product/issues/30#issuecomment-380854683) for more context).

The goal of this PR is to change this behaviour to ensure maps look the same no matter whether point aggregation is enabled or not.

Quoting @rochoa (https://github.com/CartoDB/product/issues/30#issuecomment-384020382):

> My understanding is that TurboCarto's ramps/legends should use the original data/query for the computation instead of the aggregated one. Why? Because legend must be valid across all zoom levels. If I zoom enough, I'll get to the original data.

cc: @dgaubert @jgoizueta @ivanmalagon

**Comment by dgaubert** [comment]
I've created a branch as PoC to achieve that: https://github.com/CartoDB/Windshaft-cartodb/tree/default-point-aggregation

**Comment by jgoizueta** [comment]
@dgaubert your PoC dosn't affect the new metadata stats, right? (I guess all adapters run before the stats)

**Comment by dgaubert** [comment]
Sure, adapters run before creating the map and `layer-stats` run after that. It doesn't to your implementation of layer statistics.

**Comment by dgaubert** [comment]
Closing, https://github.com/CartoDB/product/issues/30#issuecomment-404055774

**Comment by rochoa** [comment]
This still makes sense at Engine level, right?

**Comment by enekid** [comment]
Let's retake this conversation with the following example:

**Dataset**

| the_geom | cartodb_id | address | grade
| --- | --- | --- | --- |
| 0101..4440  | 1  | Gran Vía 2 | 10
| 0101..4441  | 1  | Castellana 5 | 4
...

**Aggregation**

```javascript
aggregation: {
    placement: 'point-sample',
    threshold: 1,
    columns: {
        grade_avg: { "aggregate_function": "avg", "aggregated_column": "grade" }
    },
}
```

**Use cases**


1. Use non aggregated column in ramp

```css
#layer {
    marker-fill: ramp([grade], (#d7191c, #fdae61, #abdda4, #2b83ba), quantiles);
}
```


2. Use aggregated column in ramp
```css
#layer {
    marker-fill: ramp([grade_avg], (#d7191c, #fdae61, #abdda4, #2b83ba), quantiles);
}
```


3. Bonus: Use mix of aggregated and non-aggregated columns in turbo-carto

```css
#layer {
    marker-fill: ramp([grade], (#d7191c, #fdae61, #abdda4, #2b83ba), quantiles);
    marker-width: [grade_avg]
}
```

Does this make any sense? @jgoizueta
